# Site Configuration
[site]
  title                = "Bioxiplas" # Shared title for SEO and OpenGraph
  description          = "Sustainable packaging and biodegradable protection solutions for responsible industries." # Shared description for SEO and OpenGraph
  tagline              = "Biotechnology applied to circular packaging"
  tagline_separator    = "" 
  base_url             = "https://upstart-astro.netlify.app" 
  logo                 = "/images/logobioxiplas.png" 
  logo_hover_animation = true 
  logo_text            = "" 
  logo_width           = "60px" 
  logo_height          = "60px" 
  trailing_slash       = true

  [site.favicon]
    path  = "/images/favicons" 
    image = "/images/logo.svg" 


# SEO Metadata
[seo]
  author = "Bioxiplas"
  keywords = [
    "biodegradable packaging",
    "eco-friendly materials",
    "compostable solutions",
    "sustainable industrial packaging",
    "Bioxiplas",
  ]
  robots = "index, follow"

  [seo.robots_txt]
    enable = true
    disallow = [
      "/cdn-cgi/",
    ]

  [seo.sitemap]
    enable = true
    exclude = []


# Theme Settings
[settings]
  blog_folder        = "blog" 
  integration_folder = "integration" 
  pagination         = 6 
  sticky_header      = true 

  contact_form_action   = "https://formsubmit.co/temp.gats@gmail.com" 
  contact_form_provider = "formsubmit.co"

  footer_description = "We develop certified biodegradable packaging and protective products designed for demanding industries seeking sustainability and circularity."

  [settings.copyright]
    enable = true
    text   = "© {{ year }} Bioxiplas. All rights reserved."

  [settings.subscription]
    enable      = true 
    title       = "Subscribe to discover our latest biodegradable solutions"
    form_action = "https://gmail.us11.list-manage.com/subscribe/post?u=d870b06d86c16269e4b1f9b39&amp;id=12cf0c6ac2&amp;f_id=007e61e1f0"

  [settings.multilingual]
    enable                   = true
    default_language         = "es"
    disable_languages        = [""]
    show_default_lang_in_url = false

  [settings.navigation_button]
    enable = true
    label  = "Contact us"
    url    = "/contact/"

  [settings.markup.table_of_contents]
    enable      = true
    expanded    = true
    end_level   = 5
    ordered     = false
    start_level = 1


# OpenGraph Metadata
[opengraph]
  image        = "/images/bioxiplas.png" 
  og_locale    = "en_US" 
  og_type      = "website" 
  twitter      = "" 
  twitter_card = "summary_large_image" 


# Custom Scripts
[head]
  content = """
  <!-- You can easily add this type of tracking code by updating the `config.toml` file -->
  <script defer src="/umami.is.js" data-website-id=""></script>
  """
