# Site Configuration
[site]
  title                = "Bioxiplas"
  description          = "Soluciones avanzadas en packaging y protección biodegradable para industrias responsables"
  tagline              = "Biotecnología aplicada a embalajes sostenibles"
  tagline_separator    = ""
  base_url             = "https://bioxiplas-astro.vercel.app"
  logo                 = "/images/bioxilogo.webp"
  logo_hover_animation = true
  logo_text            = ""
  logo_width           = "110px"
  logo_height          = "30px"
  trailing_slash       = true

  [site.favicon]
    path  = "/images/favicons"
    image = "/images/bioxilogo.svg"

# SEO Metadata
[seo]
  author = "Bioxiplas"
  keywords = [
    "packaging biodegradable",
    "embalajes compostables",
    "protección biodegradable",
    "soluciones sostenibles",
    "envases ecológicos",
    "economía circular",
    "Bioxiplas",
  ]
  robots = "index, follow"

  [seo.robots_txt]
    enable = true
    disallow = [
      "/cdn-cgi/",
    ]

  [seo.sitemap]
    enable = true
    exclude = []

# Theme Settings
[settings]
  blog_folder        = "blog"
  integration_folder = "productos"
  pagination         = 6
  sticky_header      = true

  contact_form_action = "https://formsubmit.co/contacto@bioxiplas.com"
  contact_form_provider = "formsubmit.co"

  footer_description = "En Bioxiplas desarrollamos soluciones de packaging y protección personal biodegradables, adaptadas a diversas industrias con un enfoque de economía circular."

  [settings.copyright]
    enable = true
    text   = "© {{ year }} Bioxiplas. Todos los derechos reservados."

  [settings.subscription]
    enable      = true
    title       = "Suscríbete para conocer nuevas soluciones sustentables"
    form_action = "https://gmail.us11.list-manage.com/subscribe/post?u=d870b06d86c16269e4b1f9b39&amp;id=12cf0c6ac2&amp;f_id=007e61e1f0"

  [settings.multilingual]
    enable                   = true
    default_language         = "es"
    disable_languages        = [""]
    show_default_lang_in_url = false

  [settings.navigation_button]
    enable = true
    label  = "Contáctanos"
    url    = "/contact/"

  [settings.markup.table_of_contents]
    enable      = true
    expanded    = true
    end_level   = 5
    ordered     = false
    start_level = 1

# OpenGraph Metadata
[opengraph]
  image        = "/images/bioxiplas.jpg"
  og_locale    = "es_CL"
  og_type      = "website"
  twitter      = "@bioxiplas"
  twitter_card = "summary_large_image"

# Head Injection (Analytics, etc.)
[head]
  content = """
  <!-- Código de seguimiento u otros scripts -->
  """
